import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <main style={{ minHeight: "calc(100vh - 136px)" }}>{children}</main>
        {/* <footer className="w-full bg-black text-white flex justify-center gap-6 h-20"></footer> */}
      </body>
    </html>
  );
}
